FROM zyuxuan0115/nightcore:main as nightcore
FROM zyuxuan0115/cpp-microservice-deps:main

COPY --from=nightcore /nightcore/launcher       /nightcore/launcher
COPY --from=nightcore /nightcore/func_worker_v1 /nightcore/func_worker_v1

ARG NUM_CPUS=1

COPY . /DeathStarBench

RUN cd /DeathStarBench/mediaMicroservices \
    && mkdir -p build \
    && cd build \
    && cmake .. \
    && make -j${NUM_CPUS}

WORKDIR /DeathStarBench/mediaMicroservices
