#!/bin/bash

#/nightcore/launcher \
#    --root_path_for_ipc=/tmp/nightcore/ipc \
#    --fprocess_mode=cpp \
#    --fprocess="/nightcore/func_worker_v1 $1" \
#    --fprocess_output_dir=/tmp/nightcore/output --func_id=$2 \
#    --v=1 &

sleep 600
echo "hello world"
