version: "3.8"
services:
  nightcore-engine:
    image: zyuxuan0115/nightcore:test2
    entrypoint:
      - /nightcore/engine
      - --gateway_addr=nightcore-gateway
      - --root_path_for_ipc=/tmp/nightcore/ipc
      - --func_config_file=/nightcore/func_config.json
      - --num_io_workers=1
      - --gateway_conn_per_worker=32
      - --disable_monitor
      - --instant_rps_p_norm=0.8
    depends_on:
      - nightcore-gateway
    volumes:
      - /mnt/inmem/nightcore:/tmp/nightcore
      - /sys/fs/cgroup:/tmp/root_cgroupfs
    environment:
      - FAAS_CGROUP_FS_ROOT=/tmp/root_cgroupfs

  nightcore-gateway:
    image: zyuxuan0115/nightcore:test2
    entrypoint:
      - sh
      - /nightcore/run_gateway
    ports: 
      - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /tmp/nightcore_config.json:/tmp/nightcore/func_config.json

  foo:
    image: zyuxuan0115/nightcore:test2
    entrypoint:
      - /nightcore/launcher
      - --func_id=1
      - --fprocess_mode=cpp
      - --fprocess_output_dir=/nightcore
      - --root_path_for_ipc=/tmp/nightcore/ipc
      - --fprocess="/nightcore/func_worker_v1 /nightcore/libfoo.so"
      - --v=1
    depends_on:
      - nightcore-engine
    volumes:
      - /mnt/inmem/nightcore:/tmp/nightcore
      - /sys/fs/cgroup:/tmp/root_cgroupfs
    environment:
      - FAAS_CGROUP_FS_ROOT=/tmp/root_cgroupfs

  bar:
    image: zyuxuan0115/nightcore:test2
    entrypoint:
      - /nightcore/launcher
      - --func_id=2
      - --fprocess_mode=cpp
      - --fprocess_output_dir=/nightcore
      - --root_path_for_ipc=/tmp/nightcore/ipc
      - --fprocess="/nightcore/func_worker_v1 /nightcore/libbar.so"
      - --v=1
    depends_on:
      - nightcore-engine
    volumes:
      - /mnt/inmem/nightcore:/tmp/nightcore
      - /sys/fs/cgroup:/tmp/root_cgroupfs
    environment:
      - FAAS_CGROUP_FS_ROOT=/tmp/root_cgroupfs

