services:
  bar:
    deploy:
      placement:
        constraints:
        - node.hostname == nightcore-worker1
      replicas: 1
  foo:
    deploy:
      placement:
        constraints:
        - node.hostname == nightcore-worker1
      replicas: 1
  nightcore-engine:
    deploy:
      placement:
        constraints:
        - node.hostname == nightcore-worker1
      replicas: 1
  nightcore-gateway:
    deploy:
      placement:
        constraints:
        - node.hostname == nightcore-manager
      replicas: 1
version: '3.8'
