services:
  bar:
    deploy:
      placement:
        constraints:
        - node.labels.engine_node == true
        max_replicas_per_node: 1
      replicas: 1
  foo:
    deploy:
      placement:
        constraints:
        - node.labels.engine_node == true
        max_replicas_per_node: 1
      replicas: 1
  nightcore-engine:
    deploy:
      placement:
        constraints:
        - node.labels.engine_node == true
        max_replicas_per_node: 1
      replicas: 2
  nightcore-gateway:
    deploy:
      placement:
        constraints:
        - node.hostname == nightcore-manager
      replicas: 1
version: '3.8'
