FROM zyuxuan0115/nightcore:test as nightcore

COPY --from=nightcore /nightcore/launcher        /nightcore/launcher
COPY --from=nightcore /nightcore/func_worker_v1  /nightcore/func_worker_v1
COPY --from=nightcore /nightcore/libfoo.so        /nightcore/libfoo.so

ARG NUM_CPUS=1

WORKDIR /nightcore
