all:
	g++ -std=c++11 -fPIC -O3 pthread_test.c -o pthread_test -lpthread 
	g++ -std=c++11 -fPIC pkey_test.c -o pkey_test -lpthread
#	g++ -std=c++11 -fPIC libmpk_test.c -o libmpk_test -lpthread -lmpt -lmpk_heaplib
